---
- name: Include vars
  ansible.builtin.include_vars:
    file: torrent.yml
    name: torrent

- name: Deploy qBittorrent configuration
  ansible.builtin.include_tasks: config.yml
  vars:
    torrent_config_src: qBittorrent.conf

- name: Create nas directory
  ansible.builtin.file:
    path: /mnt/nas
    state: directory
    mode: "0755"

- name: Mount NFS NAS
  ansible.posix.mount:
    path: /mnt/nas
    src: "jd-truenas-01.linds.com.au:/mnt/HDD"
    fstype: nfs4
    opts: defaults,rsize=1048576,wsize=1048576,noatime,nconnect=4,soft
    state: present
    boot: true
  register: mount

- name: Mount NAS if changed
  ansible.builtin.command: mount -a
  when: mount.changed
