---
- name: Install transmission + required
  ansible.builtin.yum:
    name: "{{ item }}"
    state: latest
  with_items: 
    - qbittorrent
    - qbittorrent-nox
    - cifs-utils
    - nfs-utils

- name: Stop service qbittorrent, if started
  ansible.builtin.service:
    name: qbittorrent
    state: stopped
  ignore_errors: true

- name: Stop service qbittorrent, if started
  ansible.builtin.service:
    name: "system-qbittorrent\\x2dnox.slice"
    state: stopped
  ignore_errors: true

- name: Create config directory
  ansible.builtin.file:
    path: /root/.config/qBittorrent
    state: directory
    mode: '0755'

- name: Include JD
  ansible.builtin.include_tasks:
    file: jd.yml
  when: inventory_hostname in groups['jd_torrent']

- name: Include LINDS
  ansible.builtin.include_tasks:
    file: linds.yml
  when: inventory_hostname in groups['linds_torrent']

- name: Start transmission
  ansible.builtin.service:
    name: qbittorrent-nox@root.service
    state: started
    enabled: true

- name: Set Sysctl
  ansible.posix.sysctl:
    name: net.core.rmem_max
    value: '16777216'
    sysctl_set: true

- name: Set Sysctl
  ansible.posix.sysctl:
    name: net.core.wmem_max
    value: '16777216'
    sysctl_set: true