---
- name: Install transmission + required
  ansible.builtin.yum:
    name: "{{ item }}"
    state: latest
  with_items: 
    - qbittorrent
    - qbittorrent-nox
    - cifs-utils

- name: Create nas directory
  ansible.builtin.file:
    path: /root/.config/qBittorrent
    state: directory
    mode: '0755'

- name: Copy Transmission settings
  ansible.builtin.copy:
    src: qBittorrent.conf
    dest: /root/.config/qBittorrent/qBittorrent.conf
    owner: root
    group: root
    mode: '600'
    #decrypt: true

- name: Start transmission
  ansible.builtin.service:
    name: qbittorrent-nox@root.service
    state: started
    enabled: true

- name: Include vars
  ansible.builtin.include_vars:
    file: torrent.yml
    name: torrent

- name: Create nas directory
  ansible.builtin.file:
    path: /mnt/nas
    state: directory
    mode: '0755'

- name: Mount SMB NAS
  ansible.posix.mount:
    src: "//{{ smb_server }}/{{ smb_path }}"
    path: /mnt/nas
    fstype: cifs
    opts: "username={{ torrent.smb_username }},password={{ torrent.smb_password }},domain=linds.com.au,dir_mode=0777,file_mode=0777,nounix"
    state: present
  register: mount

- name: Mount NAS if changed
  ansible.builtin.shell: "mount -a"
  when: mount.changed

- name: Set Sysctl
  ansible.posix.sysctl:
    name: net.core.rmem_max
    value: '16777216'
    sysctl_set: true

- name: Set Sysctl
  ansible.posix.sysctl:
    name: net.core.wmem_max
    value: '16777216'
    sysctl_set: true