---
roles:
- name: robertdebock.autofs
- name: robertdebock.auto_update
- name: robertdebock.epel
- name: robertdebock.ntp
- name: robertdebock.logrotate
- name: claranet.motd
collections:
- name: ansible.posix
- name: ansibleguy.opnsense
- name: community.general
- name: devsec.hardening
- name: ansibleguy.opnsense
- name: kubernetes.core
- name: arensb.truenas
- name: vyos.vyos