---
kubernetes:
  hosts:
  children:
    nodes:
      hosts:
        jd-kube-[02:04]:
        10.3.1.23:
    master:
      hosts:
        10.0.53.10:
    linds_master:
      hosts:
        10.3.1.24:
