---
kubernetes:
  hosts:
    #localhost:
  children:
    nodes:
      hosts:
        #jd-kube-03.linds.com.au
        #linds-kube-[01:02].linds.com.au
        linds-kube-02.linds.com.au
    master:
      hosts:
        #jd-kube-01.linds.com.au