---
kubernetes:
  hosts:
  children:
    nodes:
      hosts:
        jd-kube-[02:04]:
        10.3.1.22:
    master:
      hosts:
        jd-kube-01:
    linds_master:
      hosts:
        10.3.1.23:
