---
proxmox:
  children:
    jd_proxmox:
      hosts:
        jd-proxmox-01.linds.com.au:
          ansible_host: 10.0.50.246
      vars:
        proxmox_zfs_datasets:
          - name: VM/truenas-nas
            properties:
              mountpoint: /mnt/NAS
              recordsize: 1M
              compression: zstd
              atime: "off"
              acltype: posix
          - name: VM/truenas-nas/minio
            properties:
              recordsize: 1M
          - name: truenas-hdd
            properties:
              mountpoint: /mnt/HDD

        proxmox_nfs_exports:
          - path: /mnt/NAS
            options: rw,no_root_squash,insecure,no_subtree_check
            networks:
              - 10.0.50.0/24
              - 10.0.53.0/24
              - 10.3.1.0/24
              - 10.0.36.0/24
          - path: /mnt/HDD
            options: rw,anonuid=0,anongid=0,all_squash,insecure,no_subtree_check
            networks:
              - 10.0.53.0/24
              - 10.0.50.0/24

        proxmox_iscsi_targets:
          - iqn: iqn.2005-10.org.truenas:arr-suite
            portal_ip: 10.0.50.246
            portal_port: 3260
            luns:
              - name: arr-iscsi
                wwn: f41b5e6d-1ccd-400e-bff4-713ef6d53d9f
                plugin: fileio
                path: /mnt/NAS/arr-iscsi
                size: 21474840576
                write_back: true

        proxmox_sanoid_policies:
          - dataset: VM/truenas-nas
            template: ssd_short
            recursive: true
