---
- name: Install storage packages
  ansible.builtin.import_tasks: packages.yml

- name: Enforce ZFS dataset properties
  ansible.builtin.import_tasks: zfs.yml

- name: Configure NFS server
  ansible.builtin.import_tasks: nfs.yml

- name: Configure iSCSI target
  ansible.builtin.import_tasks: iscsi.yml

- name: Configure sanoid snapshots
  ansible.builtin.import_tasks: sanoid.yml

- name: Manage LXC containers
  ansible.builtin.import_tasks: lxc.yml
