---
- name: Cronjob for item
  ansible.builtin.cron:
    name: "Backup for {{ outer_item.key }} - {{ item.key }}"
    minute: "0"
    hour: "0"
    weekday: "1"
    job: "cd {{ backup_var.root_path }}{{ backup_var.backups[outer_item.key]['dest_folder'] }} && python3 {{ backup_var.backups[outer_item.key]['file'] }} {{ item.key }} {{ item.value.username }} {{ item.value.password }}"
  loop: "{{ backup_var.backups[outer_item.key]['hosts'] | dict2items }}"