---
- name: Install Git
  ansible.builtin.package:
    name: git
    state: latest

- name: Include vars
  ansible.builtin.include_vars:
    file: backup.yml
    name: backup_var

- name: Cron job to grab backups
  ansible.builtin.include_tasks:
    file: cron.yml
  loop: "{{ lookup('ansible.builtin.dict', backup_var.backups) }}"
  loop_control:
    loop_var: outer_item

- name: Clone repos required
  ansible.builtin.include_tasks:
    file: repos.yml