---
- name: Firewall IPv6 rules
  vyos.vyos.vyos_firewall_rules:
    config:
    - afi: ipv6
      rule_sets:
      - name: IPv6_WAN
        description: This is ipv6 specific rule-set
        default_action: drop
        rules:
        - number: 1
          action: accept
          description: Fwipv6-Rule 1 is configured by Ansible
          protocol: ipv6-icmp
        - number: 2
          action: accept
          description: Fwipv6-Rule 2 is configured by Ansible
          ipsec: match-ipsec
    state: merged

- name: Apply IPv6 Firewall rules
  vyos.vyos.vyos_config:
    lines:
      - set firewall interface "{{ wan_interface }}" in ipv6-name IPv6_WAN
      - set firewall interface "{{ wan_interface }}" out ipv6-name IPv6_WAN
      - set firewall interface "{{ wan_interface }}" local ipv6-name IPv6_WAN
    save: true

- name: Firewall IPv4 rules
  vyos.vyos.vyos_firewall_rules:
    config:
    - afi: ipv4
      rule_sets:
      - name: IPv4_WAN_IN
        description: IPv4 rules
        default_action: drop
        rules:
        - number: 1
          action: accept
          description: Allow ICMP
          protocol: icmp
        - number: 2
          action: accept
          description: Allow IPSEC
          ipsec: match-ipsec
        - number: 9999
          description: Allow normal
          action: accept
          state: 
            established: true
            related: true
      - name: IPv4_WAN_LOCAL
        description: IPv4 rules
        default_action: drop
        rules:
        - number: 1
          action: accept
          description: IPv4 ICMP ALLOW
          protocol: icmp
        - number: 2
          action: accept
          description: IPSEC ALLOW
          ipsec: match-ipsec
        - number: 9999
          action: accept
          state: 
            established: true
            related: true
      - name: IPv4_WAN_OUT
        description: IPv4 rules
        default_action: accept
        rules:
        - number: 1
          action: accept
          description: IPv4 ICMP ALLOW
          protocol: icmp
        - number: 2
          action: accept
          description: IPSEC ALLOW
          ipsec: match-ipsec
        - number: 9999
          action: accept
          state: 
            established: true
            related: true
    state: merged

- name: Apply IPv4 WAN Firewall rules
  vyos.vyos.vyos_config:
    lines:
      - set firewall interface "{{ wan_interface }}" in name IPv4_WAN_IN
      - set firewall interface "{{ wan_interface }}" local name IPv4_WAN_LOCAL
      - set firewall interface "{{ wan_interface }}" out name IPv4_WAN_OUT
    save: true

- name: configure hostname and domain-name
  vyos.vyos.vyos_system:
    host_name: jd-vyos-01
    domain_name: linds.com.au

- name: Set IP on LAN
  vyos.vyos.vyos_l3_interfaces:
    config:
    - name: "{{ main_lan_interface }}"
      ipv4:
      - address: 10.0.50.1/24

- name: Create DHCP for LAN
  vyos.vyos.vyos_config:
    lines:
      - set interfaces ethernet "{{ wan_interface }}" ipv6 address autoconf
      - set interfaces ethernet "{{ wan_interface }}" dhcpv6-options pd 0 length '56'
      - set interfaces ethernet "{{ wan_interface }}" dhcpv6-options pd 0 interface "{{ main_lan_interface }}" sla-id '0'
      - set interfaces ethernet "{{ wan_interface }}" dhcpv6-options rapid-commit
      - set service dhcp-server shared-network-name JD-LAN subnet 10.0.50.0/24 
      - set service dhcp-server shared-network-name JD-LAN domain-search linds.com.au
      - set service dhcp-server shared-network-name JD-LAN name-server 10.0.50.1
      - set service dhcp-server shared-network-name JD-LAN name-server 10.0.50.200
      - set service dhcp-server shared-network-name JD-LAN subnet 10.0.50.0/24 range 0 start 10.0.50.2
      - set service dhcp-server shared-network-name JD-LAN subnet 10.0.50.0/24 range 0 stop 10.0.50.199
      - set service dhcp-server shared-network-name JD-LAN subnet 10.0.50.0/24 default-router 10.0.50.1
      - set service dhcp-server shared-network-name JD-LAN domain-name linds.com.au
      - set service dhcp-server shared-network-name JD-LAN domain-search linds.com.au
      - set service dhcp-server host-decl-name
      - set service dhcp-server hostfile-update
      - set service dns forwarding listen-address 10.0.50.1
      - set service dns forwarding dhcp "{{ main_lan_interface }}"
      - set nat source rule 10 outbound-interface "{{ wan_interface }}"
      - set nat source rule 10 source address '10.0.50.0/24'
      - set nat source rule 10 translation address 'masquerade'
      - set nat source rule 10 destination group network-group !LAN-Addresses
      - set service router-advert interface "{{ main_lan_interface }}" prefix ::/56
    save: true

- name: Set up SNMP
  vyos.vyos.vyos_snmp_server:
    config:
      listen_addresses:
        - address: "10.0.50.1"

- name: Enable LLDP
  vyos.vyos.vyos_lldp_global:
    config:
      legacy_protocols:
      - fdp
      - cdp
      - edp
      - sonmp
      snmp: enable

- name: Set DNS for global
  vyos.vyos.vyos_config:
    lines:
      - set service dns forwarding domain linds.com.au name-server 192.168.6.1
      - set service dns forwarding domain linds.com.au name-server 10.3.1.200
      - set service dns forwarding domain linds.com.au name-server 10.0.50.200
      - set service dns forwarding domain linds.com.au addnta
    save: true

- name: Include WireGuard
  ansible.builtin.include_tasks:
    file: jd_wireguard.yml

- name: Include JD VLANS
  ansible.builtin.include_tasks:
    file: jd_vlan.yml

- name: Include Port Forward
  ansible.builtin.include_tasks:
    file: jd_port_forward.yml

- name: Include Site to Site
  ansible.builtin.include_tasks:
    file: jd_site_to_site.yml

- name: Include BGP
  ansible.builtin.include_tasks:
    file: jd_bgp.yml