---
- name: Minecraft Port forward
  vyos.vyos.vyos_config:
    lines:
      - set nat destination rule 20 inbound-interface eth0
      - set nat destination rule 20 protocol tcp_udp
      - set nat destination rule 20 destination port 25565
      - set nat destination rule 20 translation address '10.0.53.17'
    save: true

- name: Minecraft firewall port forward
  vyos.vyos.vyos_firewall_rules:
    config:
    - afi: ipv4
      rule_sets:
      - name: IPv4_WAN_IN
        rules:
        - number: 101
          action: accept
          description: Minecraft inbound
          protocol: tcp_udp 
          destination:
            port: 25565