- name: IPSEC Site to Site auth
  vyos.vyos.vyos_config:
    lines:
       - set pki certificate IPSEC certificate "{{ pub_key }}"
       - set pki certificate IPSEC private key "{{ priv_key }}"

- name: IPSEC Site to Site
  vyos.vyos.vyos_config:
    lines:
       - set vpn ipsec esp-group MyESPGroup proposal 1 encryption aes128
       - set vpn ipsec esp-group MyESPGroup proposal 1 hash sha1
       - set vpn ipsec esp-group MyESPGroup proposal 2 encryption aes256gcm128
       - set vpn ipsec esp-group MyESPGroup proposal 2 hash sha256
       - set vpn ipsec esp-group MyESPGroup proposal 3 encryption aes256
       - set vpn ipsec esp-group MyESPGroup proposal 3 hash sha512
       - set vpn ipsec esp-group MyESPGroup pfs disable
       - set vpn ipsec ike-group MyIKEGroup close-action restart
       - set vpn ipsec ike-group MyIKEGroup dead-peer-detection action restart
       - set vpn ipsec ike-group MyIKEGroup key-exchange 'ikev2'
       - set vpn ipsec ike-group MyIKEGroup proposal 1 dh-group 14
       - set vpn ipsec ike-group MyIKEGroup proposal 1 encryption aes256gcm128
       - set vpn ipsec ike-group MyIKEGroup proposal 1 hash sha256
       - set vpn ipsec ike-group MyIKEGroup proposal 2 dh-group 14
       - set vpn ipsec ike-group MyIKEGroup proposal 2 encryption aes256
       - set vpn ipsec ike-group MyIKEGroup proposal 3 dh-group 14
       - set vpn ipsec ike-group MyIKEGroup proposal 3 encryption aes256ccm128
       - set vpn ipsec ike-group MyIKEGroup proposal 4 dh-group 14
       - set vpn ipsec ike-group MyIKEGroup proposal 4 encryption aes256gmac
       - set vpn ipsec site-to-site peer LINDS authentication mode x509
       - set vpn ipsec site-to-site peer LINDS remote-address linds-pfsense.linds.com.au
       - set vpn ipsec site-to-site peer LINDS authentication remote-id %any
       - set vpn ipsec site-to-site peer LINDS authentication use-x509-id
       - set vpn ipsec site-to-site peer LINDS authentication x509 ca-certificate LINDS
       - set vpn ipsec site-to-site peer LINDS authentication x509 certificate IPSEC
       - set vpn ipsec site-to-site peer LINDS default-esp-group MyESPGroup
       - set vpn ipsec site-to-site peer LINDS ike-group MyIKEGroup
       - set vpn ipsec site-to-site peer LINDS local-address any
       - set vpn ipsec site-to-site peer LINDS tunnel 0 esp-group MyESPGroup
       - set vpn ipsec site-to-site peer LINDS tunnel 0 local prefix 10.0.50.0/24
       - set vpn ipsec site-to-site peer LINDS tunnel 0 local prefix 10.0.53.0/24
       - set vpn ipsec site-to-site peer LINDS tunnel 0 local prefix 10.0.10.0/24
       - set vpn ipsec site-to-site peer LINDS tunnel 0 remote prefix 192.168.6.0/24
       - set vpn ipsec site-to-site peer LINDS tunnel 0 remote prefix 10.0.0.0/24
       - set vpn ipsec site-to-site peer LINDS tunnel 0 remote prefix 10.3.1.0/24
       - set vpn ipsec site-to-site peer LINDS tunnel 0 remote prefix 10.0.36.0/24
       - set vpn ipsec site-to-site peer LINDS tunnel 0 remote prefix 10.0.80.0/24
       - set vpn ipsec site-to-site peer LINDS connection-type initiate
    save: true

- name: IPSEC Firewall
  vyos.vyos.vyos_firewall_rules:
    config:
    - afi: ipv4
      rule_sets:
      - name: IPv4_WAN_IN
        rules:
        - number: 102
          action: accept
          description: IPSEC
          protocol: tcp_udp 
          destination:
            port: 500
        - number: 103
          action: accept
          description: IPSEC
          protocol: tcp_udp 
          destination:
            port: 4500
        - number: 104
          action: accept
          description: Wifi calling
          protocol: esp
      - name: IPv4_WAN_LOCAL
        rules:
        - number: 102
          action: accept
          description: IPSEC
          protocol: tcp_udp 
          destination:
            port: 500
        - number: 103
          action: accept
          description: IPSEC
          protocol: tcp_udp 
          destination:
            port: 4500