---
- name: Plex Port forward
  vyos.vyos.vyos_config:
    lines:
      - set nat destination rule 20 inbound-interface name "{{ wan_interface }}"
      - set nat destination rule 20 protocol tcp_udp
      - set nat destination rule 20 destination port 32400
      - set nat destination rule 20 translation address 10.3.1.20
    