- name: Create BGP Peering for K8s cluster
  vyos.vyos.vyos_config:
    lines: 
      - set protocols bgp listen range 10.3.1.0/24 peer-group 'k8s'
      - set protocols bgp neighbor "{{ main_lan_interface }}".300 address-family ipv4-unicast
      - set protocols bgp neighbor "{{ main_lan_interface }}".300 interface remote-as 'external'
      - set protocols bgp peer-group k8s address-family ipv4-unicast
      - set protocols bgp peer-group k8s remote-as '64512'
      - set protocols bgp system-as '64551'
    save: true