---
- name: Plex Port forward
  vyos.vyos.vyos_config:
    lines:
      - set nat destination rule 20 inbound-interface "{{ wan_interface }}"
      - set nat destination rule 20 protocol tcp_udp
      - set nat destination rule 20 destination port 32400
      - set nat destination rule 20 translation address 10.3.1.20
    save: true

- name: Plex Port forward firewall
  vyos.vyos.vyos_firewall_rules:
    config:
    - afi: ipv4
      rule_sets:
      - name: IPv4_WAN_IN
        rules:
        - number: 101
          action: accept
          description: Plex inbound
          protocol: tcp_udp 
          destination:
            port: 32400