---
- name: Add LINDS-CA
  vyos.vyos.vyos_config:
    lines:
       - "set pki ca LINDS certificate {{ item }}"
    save: true
  with_file: linds-ca.cer

- name: Set tz
  vyos.vyos.vyos_config:
    lines:
       - "set system time-zone Australia/Melbourne"
    save: true

- name: Enable latency optimisation
  vyos.vyos.vyos_config:
    lines:
       - set interfaces ethernet "{{ wan_interface }}" offload gro
       - set interfaces ethernet "{{ wan_interface }}" offload gso
       - set interfaces ethernet "{{ wan_interface }}" offload rfs
       - set interfaces ethernet "{{ wan_interface }}" offload rps
       - set interfaces ethernet "{{ wan_interface }}" offload sg
    save: true

- name: Enable latency optimisation
  vyos.vyos.vyos_config:
    lines:
       - set interfaces ethernet "{{ main_lan_interface }}" offload gro
       - set interfaces ethernet "{{ main_lan_interface }}" offload gso
       - set interfaces ethernet "{{ main_lan_interface }}" offload rfs
       - set interfaces ethernet "{{ main_lan_interface }}" offload rps
       - set interfaces ethernet "{{ main_lan_interface }}" offload sg
    save: true

- name: Configure WAN interfaces
  vyos.vyos.vyos_interfaces:
    config:
    - name: "{{ wan_interface }}"
      description: WAN
      enabled: yes

- name: DHCP on WAN
  vyos.vyos.vyos_l3_interfaces:
    config:
    - name: "{{ wan_interface }}"
      ipv4:
      - address: dhcp
      ipv6:
      - address: dhcpv6

- name: Enable latency optimisation
  vyos.vyos.vyos_config:
    lines:
       - "set system option performance throughput"
    save: true

- name: Create firewall group
  vyos.vyos.vyos_firewall_global:
    config:
      group:
        network_group:
        - name: LAN-Addresses
          description: LAN Networks
          members:
          - address: 192.168.0.0/16
          - address: 10.0.0.0/8
          - address: 172.16.0.0/12
    state: merged

- name: configure name servers
  vyos.vyos.vyos_system: 
    name_servers:
     - 1.1.1.1
     - 1.0.0.1

- name: Set DNS for global
  vyos.vyos.vyos_config:
    lines:
      - set service dns forwarding system
      - set service dns forwarding cache-size 1000000
      - set service dns forwarding allow-from 10.0.0.0/8
      - set service dns forwarding allow-from 172.16.0.0/12
      - set service dns forwarding allow-from 192.168.0.0/16
    save: true

- name: Set Dynamic DNS
  vyos.vyos.vyos_config:
    lines:
      - set service dns dynamic address "{{ wan_interface }}" service DuckDNS host-name "{{ dyn_host }}"
      - set service dns dynamic address "{{ wan_interface }}" service DuckDNS username nouser
      - set service dns dynamic address "{{ wan_interface }}" service DuckDNS password "{{ dyn_dns }}"
      - set service dns dynamic address "{{ wan_interface }}" service DuckDNS protocol dyndns2
      - set service dns dynamic address "{{ wan_interface }}" service DuckDNS server www.duckdns.org
    save: true

- name: Set UPnP
  vyos.vyos.vyos_config:
    lines:
      - set service upnp wan-interface "{{ wan_interface }}"
      - set service upnp listen "{{ main_lan_interface }}"
      - set service upnp nat-pmp
    save: true

- name: Set up firewall
  vyos.vyos.vyos_firewall_global:
    config:
      validation: disable
      log_martians: true
      syn_cookies: true
      twa_hazards_protection: true
      ping:
        all: true
        broadcast: true
      state_policy:
      - connection_type: established
        action: accept
        log: false
      - connection_type: invalid
        action: accept
        log: false

- name: Run JD VyOS
  ansible.builtin.include_tasks:
    file: jd.yml
  when: inventory_hostname == "10.0.50.1"

- name: Run JD VyOS
  ansible.builtin.include_tasks:
    file: linds.yml
  when: inventory_hostname == "192.168.6.1"