# Managed by LINDS-Ansible: roles/router/files/etc/snmp/snmpd.conf.
agentaddress udp:10.0.50.1:161,udp:10.0.53.1:161
rocommunity public default
sysLocation jd-router-01
sysContact root
sysServices 72

# lldpd's SNMP subagent.
master agentx
agentXSocket /var/agentx/master
