---
- name: Include kubernetes vars
  ansible.builtin.include_vars:
    file: vars.yml
    name: k8s_var

- name: Include RedHat-specific tasks
  ansible.builtin.include_tasks:
    file: redhat.yml
  when: ansible_facts['os_family'] == "RedHat"

- name: Include Debian-specific tasks
  ansible.builtin.include_tasks:
    file: debian.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Create containers folder
  ansible.builtin.file:
    path: /etc/containers/
    state: directory

- name: Check if swap enabled
  changed_when: false
  ansible.builtin.command: awk '{ if (NR > 1) exit 1}' /proc/swaps
  register: swap_enabled
  ignore_errors: true

- name: Disable swap if not disabled
  ansible.builtin.command: swapoff -a
  when: swap_enabled.rc != 0

- name: Remove swap from fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    state: absent
    regexp: \sswap\s

- name: Check if ip_forward enabled
  changed_when: false
  ansible.builtin.command: grep 1 /proc/sys/net/ipv4/ip_forward
  register: ip_forward_enabled
  failed_when: ip_forward_enabled.rc >=2

- name: Enable ip_forward
  ansible.builtin.shell: echo 1 > /proc/sys/net/ipv4/ip_forward
  when: ip_forward_enabled.rc == 1

- name: Check if br_filter enabled
  changed_when: false
  ansible.builtin.command: grep 1 /proc/sys/net/bridge/bridge-nf-call-iptables
  register: br_filter_enabled
  failed_when: br_filter_enabled.rc > 2

- name: Enable br_filter
  ansible.builtin.command: modprobe br_netfilter
  when: br_filter_enabled.rc != 0

- name: Check if kubectl autocomple
  changed_when: false
  ansible.builtin.command: test -f /etc/bash_completion.d/kubectl
  register: kubectl_autocomplete_enabled
  failed_when: kubectl_autocomplete_enabled.rc >=2

- name: Enable kubectl autocomplete
  ansible.builtin.shell: kubectl completion bash | sudo tee /etc/bash_completion.d/kubectl > /dev/null
  when: kubectl_autocomplete_enabled.rc == 1
  failed_when: kubectl_autocomplete_enabled.rc >=2

- name: Enable kubectl in user bashrc
  ansible.builtin.shell: |
    echo "source <(kubectl completion bash)" >> ~/.bashrc
  when: kubectl_autocomplete_enabled.rc == 1

- name: Test if joined to kubernetes cluster
  changed_when: false
  ansible.builtin.command: test -f /etc/kubernetes/kubelet.conf
  register: kubernetes_joined
  failed_when: kubernetes_joined.rc >=2

- name: Add KUBECONFIG to env
  ansible.builtin.lineinfile:
    path: /root/.bashrc
    regexp: ^export KUBECONFIG
    line: export KUBECONFIG=/etc/kubernetes/admin.conf

- name: Create kubernetes cluster check
  ansible.builtin.shell: export KUBECONFIG=/etc/kubernetes/admin.conf; kubectl get nodes | grep -i {{ ansible_facts['nodename'] }}
  register: create_cluster
  when: inventory_hostname in groups['master']
  ignore_errors: true
  become_user: root

- name: Create kubernetes cluster
  ansible.builtin.command: kubeadm init --pod-network-cidr 10.244.0.0/16 --token-ttl 0
  when: inventory_hostname in groups['master'] and create_cluster.rc!=0
  register: kube_create_cluster_output

- name: Create kubernetes join command
  ansible.builtin.command: kubeadm token create --print-join-command --v=5
  register: kubernetes_join_command
  when: inventory_hostname in groups['master']

- name: Print return information from the previous task
  ansible.builtin.debug:
    var: hostvars[groups['master'][0]]['kubernetes_join_command']
  when: inventory_hostname in groups['master']

- name: Join Kubernetes cluster
  ansible.builtin.command: "{{ hostvars[groups['master'][0]]['kubernetes_join_command']['stdout'] }}"
  when:
    - kubernetes_joined.rc != 0
    - inventory_hostname not in groups['master']

- name: Cleanup old unused images
  ansible.builtin.cron:
    name: Cleanup old images
    special_time: weekly
    job: crictl rmi --prune

- name: Setup Master
  ansible.builtin.include_tasks:
    file: master.yml
  when: inventory_hostname in groups['master']
