---
- name: Git checkout
  ansible.builtin.git:
    repo: https://github.com/Jayden-Lind/LINDS-Kubernetes.git
    dest: "{{ k8s_var.local_k8s_dir }}"
  ignore_errors: true

- name: Copy LINDS secret
  ansible.builtin.copy:
    src: linds-secret.yml
    dest: "{{ k8s_var.local_k8s_dir }}base/linds-secret.yml"
    owner: root
    group: root
    mode: "0600"
    decrypt: true

- name: Ensure bash completion is sourced in .bashrc
  lineinfile:
    path: /root/.bashrc
    line: "source /etc/bash_completion"
    state: present
    create: yes
    insertafter: EOF

- name: Configure git
  community.general.git_config:
    name: user.email
    scope: global
    value: jaydenlind@gmail.com

- name: Configure git
  community.general.git_config:
    name: user.name
    scope: global
    value: Jayden Lind
