---
- name: Git checkout
  ansible.builtin.git:
    repo: https://github.com/Jayden-Lind/LINDS-Kubernetes.git
    dest: "{{ k8s_var.local_k8s_dir }}"
  ignore_errors: true

- name: Copy LINDS secret
  ansible.builtin.copy:
    src: linds-secret.yml
    dest: "{{ k8s_var.local_k8s_dir }}base/linds-secret.yml"
    owner: root
    group: root
    mode: "0600"
    decrypt: true

- name: Ensure prerequisites
  ansible.builtin.apt: { name: ["curl", "gnupg", "apt-transport-https", "ca-certificates"], state: present, update_cache: true }
  become: true

- name: Ensure keyrings dir
  ansible.builtin.file: { path: /usr/share/keyrings, state: directory, mode: "0755" }
  become: true

- name: Add Helm repo key (dearmored) if missing
  ansible.builtin.shell: "curl -fsSL https://packages.buildkite.com/helm-linux/helm-debian/gpgkey | gpg --dearmor -o /usr/share/keyrings/helm.gpg"
  args: { creates: /usr/share/keyrings/helm.gpg }
  changed_when: true
  become: true

- name: Add Helm APT repo (signed-by)
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/helm.gpg] https://packages.buildkite.com/helm-linux/helm-debian/any/ any main"
    filename: "helm-stable-debian"
    state: present
    update_cache: true
  become: true

- name: Install Helm
  ansible.builtin.apt: { name: helm, state: present, update_cache: true }
  become: true

- name: Ensure bash completion is sourced in .bashrc
  ansible.builtin.lineinfile:
    path: /root/.bashrc
    line: source /etc/bash_completion
    state: present
    create: true
    insertafter: EOF

- name: Configure git
  community.general.git_config:
    name: user.email
    scope: global
    value: jaydenlind@gmail.com

- name: Configure git
  community.general.git_config:
    name: user.name
    scope: global
    value: Jayden Lind
