---
- name: CRI-O Repo
  ansible.builtin.copy:
    src: cri-o.repo
    dest: /etc/yum.repos.d/devel_cri_1.24.repo
    owner: root
    group: root
    mode: "0644"

- name: Kubernetes Repo
  ansible.builtin.copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
    owner: root
    group: root
    mode: "0644"

- name: Ensure Kubernetes is installed (RedHat)
  ansible.builtin.dnf:
    name: kubelet
    state: latest
    disable_excludes: all
    nobest: true

- name: Ensure K8s packages installed (RedHat)
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: latest
    disable_excludes: all
  with_items:
    - kubeadm
    - kubectl
    - cri-o
    - nfs-utils

- name: Ensure K8s services are started (RedHat)
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    state: started
  with_items:
    - kubelet
    - crio
    - cri-o

- name: Containers Policy for RHEL 9
  ansible.builtin.copy:
    src: policy.json
    dest: /etc/containers/policy.json
    owner: root
    group: root
    mode: "0644"

- name: Install git (RedHat masters)
  ansible.builtin.dnf:
    state: latest
    name: git
  when: inventory_hostname in groups['master']
  ignore_errors: true

