---
- name: Include terraform tasks
  ansible.builtin.include_tasks:
    file: terraform.yml

- name: Mount NFS Truenas
  ansible.builtin.include_role:
    name: robertdebock.autofs
  vars:
    autofs_maps:
      - name: JD_truenas_terraform{{ server }}
        mountpoint: /mnt/
        options:
          - "--timeout 60"
          - "--ghost"
        directories:
          - server: "{{ server }}:{{ path }}"
            options:
              - "fstype=nfs4"
              - "dir_mode=0777"
              - "file_mode=0777"
              - "vers=4.2"
              - "soft"
            path: "NAS"
