---
- name: Include terraform vars
  ansible.builtin.include_vars:
    file: main.yml
    name: vars

- name: Add Hashicorp Repo
  ansible.builtin.yum_repository:
    name: Hashicorp
    description: Hashicorp
    baseurl: "https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable"
    gpgkey: "https://rpm.releases.hashicorp.com/gpg"
    gpgcheck: true

- name: Ensure packages is installed
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: latest
  with_list: " {{ vars.packages }}"

- name: Clone GitHub repo
  ansible.builtin.git:
    repo: https://github.com/Jayden-Lind/LINDS-Terraform.git
    dest: "{{ vars.root_dir }}LINDS-Terraform"
  ignore_errors: true

- name: Fix Path for Packer
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    line: "export PATH=/usr/bin:$PATH"
