---
- name: Install required packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: latest
  with_list: "{{ansible_vars.packages}}"

- name: Install bottle python package
  ansible.builtin.pip:
    name: argcomplete
    state: present
    extra_args: --user

- name: Install SSH python libraries
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
  with_items: 
  - paramiko
  - ansible-pylibssh

- name: Clone LINDS Ansible
  ansible.builtin.git:
    repo: https://github.com/Jayden-Lind/LINDS-Ansible.git
    dest: "{{ vars.root_dir }}LINDS-Ansible"
  ignore_errors: true

- name: Copy private key
  ansible.builtin.copy:
    dest: /root/.ssh/id_rsa
    content: "{{ ansible_vars.ssh_private_key }}"
    owner: root
    group: root
    mode: '0600'

