---
- name: Install Ansible Pip packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - python3-argcomplete
    - python3-paramiko
    - pipx

- name: Clone LINDS Ansible
  ansible.builtin.git:
    repo: https://github.com/Jayden-Lind/LINDS-Ansible.git
    dest: "{{ vars.root_dir }}/LINDS-Ansible"
  ignore_errors: true

- name: Install Ansible reqs
  ansible.builtin.command: ansible-galaxy install -r {{ vars.root_dir }}/LINDS-Ansible/requirements.yml
- name: Copy private key
  ansible.builtin.copy:
    dest: /home/jayden/.ssh/id_rsa
    content: "{{ ansible_vars.ssh_private_key }}"
    owner: jayden
    group: jayden
    mode: "0600"
