---
- name: Install | Package management configuration {{ rhbase_package_manager }}
  template:
    src: "etc_{{ rhbase_package_manager }}_{{ item }}.j2"
    dest: "/etc/{{ rhbase_package_manager }}/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ rhbase_updates_config }}"
  notify: restart updates

- name: Updates | Ensure automatic updates service is running
  service:
    name: "{{ rhbase_updates_service }}"
    state: started
    enabled: true
