---
- name: Include EPEL Repo
  ansible.builtin.include_role:
    name: robertdebock.epel

- name: Install bash_completeion
  ansible.builtin.dnf:
    name: bash-completion
    state: latest
  ignore_errors: true

- name: Install common packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: latest
  ignore_errors: true
  with_items:
    - qemu-guest-agent

- name: Start qemu-guest-agent
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - qemu-guest-agent
  ignore_errors: true

- name: Enable Auto Update
  ansible.builtin.include_role:
    name: robertdebock.auto_update
  vars:
    auto_update_apply_updates: true
    auto_update_message: true

- name: Enable NTP
  ansible.builtin.include_role:
    name: robertdebock.ntp
  vars:
    ntp_pool:
      - name: 0.au.pool.ntp.org iburst
      - name: 1.au.pool.ntp.org iburst
      - name: 2.au.pool.ntp.org iburst
      - name: 3.au.pool.ntp.org iburst
    ntp_timezone: Australia/Melbourne

- name: MOTD
  ansible.builtin.include_role:
    name: claranet.motd
  vars:
    motd_template: "{{ ansible_parent_role_paths[0] }}/template/motd"

- name: Logrotate
  ansible.builtin.include_role:
    name: robertdebock.logrotate
  vars:
    logrotate_compress: true
    logrotate_keep: 7
    logrotate_frequency: daily
    logrotate_dateext: true

- name: Include authorized_keys
  ansible.posix.authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', 'authorized_keys') }}"

- name: Include updating trust
  ansible.builtin.include_tasks:
    file: certificates.yml

- name: Ensure remote rsyslog config
  ansible.builtin.copy:
    dest: /etc/rsyslog.d/90-remote.conf
    content: |
      *.* @(o)172.16.1.23:1514;RSYSLOG_SyslogProtocol23Format
    owner: root
    group: root
    mode: '0644'
  notify: Restart rsyslog

- name: Copy UseDNS SSHD
  ansible.builtin.copy:
    src: 02-disabledns.conf
    dest: /etc/ssh/sshd_config.d
  register: sshd

- name: Stop and disable useless services
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  with_items:
    - firewalld

- name: Restart SSHD
  ansible.builtin.command: systemctl restart sshd
  when: sshd.changed

- name: Disable mitigations
  ansible.builtin.command: grubby --update-kernel=ALL --args="mitigations=off"
