---
- name: Copy files periodically to TrueNAS
  ansible.builtin.cron:
    name: Copy Plex backup {{ item }} to TrueNAS
    minute: "0"
    hour: "2"
    job: cp -p {{ plex_base_dir | regex_replace(' ', '\ ') }}{{ item }} /mnt/truenas{{ truenas_plex_path }}{{ item }}
  with_items: "{{ plex_files_backup }}"

- name: Check if files need to be copied across
  ansible.builtin.stat:
    path: "{{ plex_base_dir }}/present"
  register: st

- name: Copy files from NAS if they don't exist locally
  ansible.builtin.copy:
    src: /mnt/truenas{{ truenas_plex_path }}{{ item | regex_replace("\\ ", " ") }}
    dest: '{{ plex_base_dir }}{{ item | regex_replace("\\ ", " ") }}'
    remote_src: true
    mode: preserve
  with_items: "{{ plex_files_backup }}"
  when: st['stat']['exists'] == false

- name: Create file indicate copy done
  ansible.builtin.file:
    path: "{{ plex_base_dir }}/present"
    state: touch
  when: st['stat']['exists'] == false

- name: Restart Plex
  ansible.builtin.command: systemctl restart plexmediaserver
  when: st['stat']['exists'] == false
