---
- name: Include plex
  import_playbook: plex.yml

- name: Include k8s
  import_playbook: kubernetes.yml

- name: Include backup
  import_playbook: backup.yml

- name: Include terraform
  import_playbook: terraform.yml

- name: Include ansible
  import_playbook: ansible.yml