---
- name: Include plex
  ansible.builtin.import_playbook: plex.yml

- name: Include k8s
  ansible.builtin.import_playbook: kubernetes.yml

- name: Include backup
  ansible.builtin.import_playbook: backup.yml

- name: Include terraform
  ansible.builtin.import_playbook: terraform.yml

- name: Include ansible
  ansible.builtin.import_playbook: ansible.yml

- name: Include torrent
  ansible.builtin.import_playbook: torrent.yml

- name: Include dev
  ansible.builtin.import_playbook: dev.yml
