---
torrent_packages_debian:
  - qbittorrent-nox
  - cifs-utils
  - nfs-common

torrent_packages_redhat:
  - qbittorrent
  - qbittorrent-nox
  - cifs-utils
  - nfs-utils

torrent_service_name: qbittorrent-nox@root.service

torrent_config_dir: /root/.config/qBittorrent

torrent_sysctl_file: /etc/sysctl.d/99-torrent.conf

torrent_sysctl_settings:
  net.core.rmem_max: "33554432"
  net.core.wmem_max: "33554432"
  net.core.rmem_default: "262144"
  net.core.wmem_default: "262144"

  net.core.netdev_max_backlog: "16384"
  net.core.somaxconn: "1024"

  net.ipv4.ip_local_port_range: "10240 65535"

  net.ipv4.tcp_fin_timeout: "15"

  net.ipv4.tcp_keepalive_time: "120"
  net.ipv4.tcp_keepalive_intvl: "30"
  net.ipv4.tcp_keepalive_probes: "5"

  net.ipv4.tcp_syncookies: "1"

  net.ipv4.tcp_mtu_probing: "1"

  vm.dirty_ratio: "15"
  vm.dirty_background_ratio: "5"
  vm.swappiness: "10"
